### ISSUE TITLE
Issue downloading modified save 

### ISSUE THREAD

**Issue by mr-andrej** [Redmega/bitburner-save-editor#11]
Hello hello, love what you're doing! I was just giving your fun little tool a spin but sadly without much success. Clicking the download button doesn't produce anything other than an error in the console.

file.store.ts:134 Uncaught TypeError: Cannot read properties of null (reading 'groups')
    at downloadFile (file.store.ts:134:15)
    at Be (action.ts:65:16)
    at ObservableObject.key (action.ts:46:16)
    at Object.He (react-dom.production.min.js:52:317)
    at Qe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at jr (react-dom.production.min.js:100:68)
    at Nr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ie (react-dom.production.min.js:292:189)
    
I might look into it myself later tonight but that's only if I manage to finish my work. Any ideas why I might be getting this issue?

**Comment by Redmega** [comment]
Closing as someone's created an active fork: https://github.com/Marcinator2/bitburner-save-editor-v2
