### ISSUE TITLE
the website cant read the json savefile??

### ISSUE THREAD

**Issue by ghost** [Redmega/bitburner-save-editor#12]
whenever i try to upload the json savefile i exported from the game and extracted thru  7zip i get this error

"Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
VM141:1 Uncaught (in promise) SyntaxError: Unexpected token 'r', "r ++[  ޭ&"... is not valid JSON
    at JSON.parse (<anonymous>)
    at file.store.ts:75:49
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at br (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:25:9)
(anonymous) @ file.store.ts:75
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
br @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
Promise.then (async)
br @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ file-loader.tsx:10
He @ react-dom.production.min.js:52
Qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
jr @ react-dom.production.min.js:100
Nr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ie @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Zt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
Show 24 more frames
Show less"

i dont know if its my browser or not but please help me!

**Comment by Redmega** [comment]
It's been a minute since I've worked on this :) seems like the save file format changed

**Comment by Redmega** [comment]
Closing as someone has created an active fork: Closing as someone's created an active fork: https://github.com/Marcinator2/bitburner-save-editor-v2
